version: '3.3'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./app:/app
  env_file:
  - ./.env.dev

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  - ./init_mysql:/docker-entrypoint-initdb.d
  env_file:
  - ./.env.db

volumes:
  mysql:
  mysql_config:
